[package]
name = 'BloomeR'
version = '0.1.0'
edition = '2021'

[lib]
crate-type = [ 'staticlib' ]
name = 'BloomeR'

[dependencies]
bit-vec = { version = "0.6", features = ["serde"] }
extendr-api = '*'
fasthash = "0.4.0"
serde = {version ="1.0.156", features = ["derive"] }
serde_json = "1.0.94"
