# Generated by extendr: Do not edit by hand
#
# This file was created with the following call:
#   .Call("wrap__make_BloomeR_wrappers", use_symbols = TRUE, package_name = "BloomeR")

#' @docType package
#' @usage NULL
#' @useDynLib BloomeR, .registration = TRUE
NULL

BloomFilter <- new.env(parent = emptyenv())

BloomFilter$new <- function(filter_size, n_hashes) .Call(wrap__BloomFilter__new, filter_size, n_hashes)

BloomFilter$add <- function(strings) invisible(.Call(wrap__BloomFilter__add, self, strings))

BloomFilter$check <- function(strings) .Call(wrap__BloomFilter__check, self, strings)

BloomFilter$frac_filled <- function() .Call(wrap__BloomFilter__frac_filled, self)

BloomFilter$print <- function() invisible(.Call(wrap__BloomFilter__print, self))

BloomFilter$clear <- function() invisible(.Call(wrap__BloomFilter__clear, self))

BloomFilter$save <- function(path) invisible(.Call(wrap__BloomFilter__save, self, path))

BloomFilter$load <- function(path) .Call(wrap__BloomFilter__load, path)

#' @export
`$.BloomFilter` <- function (self, name) { func <- BloomFilter[[name]]; environment(func) <- environment(); func }

#' @export
`[[.BloomFilter` <- `$.BloomFilter`

